name: CI
on: [push]
jobs:
  check:
    name: Checks and lints
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check Rust formatting
        run: |
          nix develop --command \
            cargo fmt --check
  build_and_test:
    name: Build and test
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Set up Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: monkey-script-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: |
          nix develop --command \
            cargo test
      - name: Build
        run: nix build
